### ISSUE TITLE
by version, the program does not work

### ISSUE THREAD

**Issue by Wetn07** [sunwinbus/tpc-truckersmp#2]
it stopped working after the last update, it was working fine before, can you renew it

**Comment by sunwinbus** [comment]
> it stopped working after the last update, it was working fine before, can you renew it

Just had a test on ETS2 v1.52.0.6 with TruckersMP. It works fine.

Please check if there is new line `Camera state saved.` in game console after pressing Alt+F12,

**Comment by Wetn07** [comment]
================= TPC For TruckersMP =================
Usage: 0.Type g_debug_camera 1 in console (only once)
       1.Alt+F12 to save coordinate of freecam
       2.Make a quicksave & reload 5 seconds later
Email: sunwinbus@ets666.com | Discord: sunwinbus#1343
Thanks to DF-41 for his great idea!
======================================================
Monitoring: C:\Users\Uzumer\Documents\Euro Truck Simulator 2\profiles
Monitoring: C:\Users\Uzumer\Documents\Euro Truck Simulator 2\profiles\416E6E656D53706563\save
Target:(-18335.5,29.4663,-11777.1) (0.991179;-0.132364,-0.00650672,-0.000868921)
Updated: C:\Users\Uzumer\Documents\Euro Truck Simulator 2\profiles\416E6E656D53706563\save\quicksave\game.sii
Fatal error, stop working!
*******************************
*     SII Decrypt Program     *
*   (c) 2016 Frantisek Milt   *
*******************************
 
 It writes this and it doesn't work

**Comment by sunwinbus** [comment]
It's the decryptor side issue. I can do nothing on it.
Probably, it's because you are using some local mods which contain float numbers (in IEEE754 format) that are larger than 1, and the decryptor doesn't support them. You may give feedback to the the author of SII Decrypt [here](https://github.com/TheLazyTomcat/SII_Decrypt).
